HW2/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :microposts
  resources :users
end

HW2/app/models/micropost.rb
class Micropost < ApplicationRecord
    belongs_to:user
end

HW2/app/models/user.rb
class User < ApplicationRecord
    has_many :micropst
end

HW2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

HW2/app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    before_action :set_micropost, only: [:show, :edit, :update, :destroy]
  

    def index
      @microposts = Micropost.all
    end
  
    
    def show
    end
  
   
    def new
      @micropost = Micropost.new
      @users = User.all
    end
  
   
    def edit
      @users = User.all
    end
  
  
    def create
      @micropost = Micropost.new(micropost_params)
  
      respond_to do |format|
        if @micropost.save
          format.html { redirect_to @micropost, notice: 'Success create' }
          format.json { render :show, status: :created, location: @micropost }
        else
          format.html { render :new }
          format.json { render json: @micropost.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def update
      respond_to do |format|
        if @micropost.update(micropost_params)
          format.html { redirect_to @micropost, notice: 'Success update' }
          format.json { render :show, status: :ok, location: @micropost }
        else
          format.html { render :edit }
          format.json { render json: @micropost.errors, status: :unprocessable_entity }
        end
      end
    end
  
   
    def destroy
      @micropost.destroy
      respond_to do |format|
        format.html { redirect_to microposts_url, notice: 'Success destroy.' }
        format.json { head :no_content }
      end
    end
  
    private
      def set_micropost
        @micropost = Micropost.find(params[:id])
      end
      def micropost_params
        params.require(:micropost).permit(:content, :user_id)
      end
end

HW2/app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]


  def index
    @users = User.all
    @microposts = Micropost.all
  end


  def show
    @microposts_of_user = Micropost.where("user_id=?",@user.id)
  end


  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Success create' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Success update' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Success destroy' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email)
    end
end

HW2/app/helpers/micropost_helper.rb
module MicropostHelper
end

HW2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

HW2/app/views/micropost/_form.html.erb
<%= form_with(model: micropost, local: true) do |form| %>
    <% if micropost.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>
  
        <ul>
          <% micropost.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :content %>
      <%= form.text_area :content %>
    </div>
  
    <div class="field">
    <%= form.label :"User ID" %>
    <% options = options_from_collection_for_select(@users,:id,:id,@micropost.id) %>
    <%= form.select :user_id,  options %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

HW2/app/views/micropost/edit.html.erb
<h1>Editing Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

HW2/app/views/micropost/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Microposts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.content %></td>
        <td><%= micropost.user_id %></td>
        <td><%= link_to 'Show', micropost %></td>
        <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
        <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Micropost', new_micropost_path %>

HW2/app/views/micropost/new.html.erb
<h1>New Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Back', microposts_path %>

HW2/app/views/micropost/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @micropost.user_id %>
</p>

<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>

HW2/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
  
        <ul>
          <% user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
  
    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

HW2/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

HW2/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New User', new_user_path %>

HW2/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

HW2/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<h1>User</h1>
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<%= link_to 'Edit', edit_user_path(@user) %> |

<%= link_to 'Back', users_path %>
<h1>Microposts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microposts_of_user.each do |micropost| %>
      <tr>
        <td><%= micropost.content %></td>
        <td><%= micropost.user_id %></td>
        <td><%= link_to 'Show', micropost %></td>
        <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
        <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Micropost', new_micropost_path %>